-- ============================================================================
-- phase-19c8a-assistant-foundation.sql
-- ----------------------------------------------------------------------------
-- Phase 19c.8a — PM Assistant foundation.
--
-- The chat-based bookkeeping bot Caleb described: morning scan turns into
-- threads, each thread is a conversation with action buttons (Send /
-- Snooze / Resolve), preview cards (PDF embed), free-text replies.
-- Same framework will host invoice scenarios, contract-lifecycle
-- scenarios, freeze-awareness, and eventually email-to-chat deep-links.
--
-- TABLES (4)
--   assistant_threads     ← one per active concern (one invoice, one contract,
--                            one overdue chase, one user-initiated topic)
--   assistant_messages    ← every back-and-forth message in each thread
--   assistant_scenarios   ← registry of scenario types (extensible)
--   assistant_followups   ← scheduled "ask me about X on date Y" reminders
--
-- RPCs (5)
--   assistant_scan_now()              — fires all scenario checks now
--   assistant_list_threads()          — open threads with unread + last msg
--   assistant_thread_messages(t_id)   — full message history for one thread
--   assistant_post_message(t_id, …)   — user posts a reply
--   assistant_action(t_id, action, …) — executes a button click + logs it
--
-- CRON
--   assistant-daily-scan @ 16:00 UTC (one hour before the existing
--   recurring-invoice cron, so by the time the user opens up the chat
--   the morning's threads are already waiting)
-- ============================================================================

BEGIN;

-- ─── 1. assistant_scenarios — registry ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assistant_scenarios (
  scenario_key  text PRIMARY KEY,
  label         text NOT NULL,         -- "Invoice ready to send"
  icon          text,                  -- emoji or icon name for the UI
  enabled       boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.assistant_scenarios (scenario_key, label, icon) VALUES
  ('invoice_ready_to_send',  'Invoice ready to send',         '📨'),
  ('invoice_overdue',        'Invoice overdue',                '⏰'),
  ('payment_expected',       'Payment expected on date',       '💵'),
  ('contract_waiting_payment','Contract waiting on payment',   '📋'),
  ('contract_expiring_soon', 'Contract expiring soon',         '🟠'),
  ('contract_frozen',        'Client on freeze',               '❄️'),
  ('user_initiated',         'You started this',               '✏️')
ON CONFLICT (scenario_key) DO NOTHING;


-- ─── 2. assistant_threads ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assistant_threads (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scenario_key   text NOT NULL REFERENCES public.assistant_scenarios(scenario_key),

  -- Display
  title          text NOT NULL,                -- "Send INV-YAN-019 to Daniel Yang"
  subtitle       text,                         -- "$1,200.00 · auto-created today"

  -- Linked entities (one is set, others null)
  invoice_id     uuid REFERENCES public.invoices(id)  ON DELETE SET NULL,
  receipt_id    uuid REFERENCES public.sales_receipts(id) ON DELETE SET NULL,
  paycheque_id   uuid REFERENCES public.paycheques(id) ON DELETE SET NULL,
  contract_id    uuid,                         -- contracts table FK (no cascade-safe ref shape)
  client_id      uuid REFERENCES public.clients(id) ON DELETE SET NULL,

  -- Lifecycle
  status         text NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open','awaiting_user','snoozed','resolved','dismissed')),
  snoozed_until  timestamptz,
  resolved_at    timestamptz,
  resolved_by    uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Unread badge
  unread_for_user boolean NOT NULL DEFAULT true,

  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  -- Free-form payload (scenario-specific context)
  context        jsonb DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_assist_threads_owner_open
  ON public.assistant_threads(owner_user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_assist_threads_invoice
  ON public.assistant_threads(invoice_id) WHERE invoice_id IS NOT NULL;


-- ─── 3. assistant_messages ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assistant_messages (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id      uuid NOT NULL REFERENCES public.assistant_threads(id) ON DELETE CASCADE,
  -- 'bot' = generated by the assistant; 'user' = typed/clicked by the admin
  role           text NOT NULL CHECK (role IN ('bot','user','system')),
  -- 'text' = plain message; 'actions' = clickable buttons (in metadata.actions);
  -- 'preview' = rich card (metadata.preview_url / metadata.title); 'event' = system
  content_type   text NOT NULL DEFAULT 'text' CHECK (content_type IN ('text','actions','preview','event')),
  content        text,
  metadata       jsonb DEFAULT '{}'::jsonb,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assist_msgs_thread
  ON public.assistant_messages(thread_id, created_at);


-- ─── 4. assistant_followups ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assistant_followups (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id      uuid NOT NULL REFERENCES public.assistant_threads(id) ON DELETE CASCADE,
  due_at         timestamptz NOT NULL,
  reason         text,
  fired_at       timestamptz,           -- null until fired
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assist_followups_due
  ON public.assistant_followups(due_at) WHERE fired_at IS NULL;


-- ─── 5. RLS — admin only for now (multi-user later) ─────────────────────
ALTER TABLE public.assistant_threads   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistant_messages  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistant_followups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistant_scenarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin reads own threads" ON public.assistant_threads;
CREATE POLICY "admin reads own threads" ON public.assistant_threads
  FOR SELECT TO authenticated
  USING (public.is_admin() AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "admin writes own threads" ON public.assistant_threads;
CREATE POLICY "admin writes own threads" ON public.assistant_threads
  FOR ALL TO authenticated
  USING (public.is_admin() AND owner_user_id = auth.uid())
  WITH CHECK (public.is_admin() AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "admin reads messages in own threads" ON public.assistant_messages;
CREATE POLICY "admin reads messages in own threads" ON public.assistant_messages
  FOR SELECT TO authenticated
  USING (public.is_admin() AND EXISTS (
    SELECT 1 FROM public.assistant_threads t
    WHERE t.id = thread_id AND t.owner_user_id = auth.uid()));

DROP POLICY IF EXISTS "admin writes messages in own threads" ON public.assistant_messages;
CREATE POLICY "admin writes messages in own threads" ON public.assistant_messages
  FOR ALL TO authenticated
  USING (public.is_admin() AND EXISTS (
    SELECT 1 FROM public.assistant_threads t
    WHERE t.id = thread_id AND t.owner_user_id = auth.uid()))
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "anyone reads scenarios" ON public.assistant_scenarios;
CREATE POLICY "anyone reads scenarios" ON public.assistant_scenarios
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin manages followups" ON public.assistant_followups;
CREATE POLICY "admin manages followups" ON public.assistant_followups
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());


-- ─── 6. Scenario detector: invoice_ready_to_send ─────────────────────────
-- Finds invoices that exist + are unsent (no EMAIL_FINANCIAL_DOC_SENT in
-- audit_logs) + are open + were created recently (within 7d). Avoids
-- creating duplicate threads for the same invoice.
-- ────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.assistant_detect_invoice_ready_to_send(
  p_owner_user_id uuid
)
RETURNS int
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  v_inv record;
  v_thread_id uuid;
  v_count int := 0;
BEGIN
  FOR v_inv IN
    SELECT i.id, i.invoice_number, i.total_cents, i.balance_due_cents,
           i.client_id, i.invoice_date, i.created_at,
           COALESCE(c.billing_contact_name, c.full_name) AS recipient_label
    FROM public.invoices i
    LEFT JOIN public.clients c ON c.id = i.client_id
    WHERE i.status = 'open'
      AND i.invoice_date <= current_date            -- not future-dated
      AND i.created_at >= now() - interval '14 days' -- only recent (avoid backfill spam)
      AND NOT EXISTS (
        SELECT 1 FROM public.audit_logs a
        WHERE a.action = 'EMAIL_FINANCIAL_DOC_SENT'
          AND a.entity_id = i.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.assistant_threads t
        WHERE t.invoice_id = i.id
          AND t.status IN ('open','awaiting_user','snoozed')
          AND t.owner_user_id = p_owner_user_id
      )
  LOOP
    INSERT INTO public.assistant_threads (
      owner_user_id, scenario_key, title, subtitle,
      invoice_id, client_id, status, context
    ) VALUES (
      p_owner_user_id,
      'invoice_ready_to_send',
      'Send ' || v_inv.invoice_number || ' to ' || COALESCE(v_inv.recipient_label, 'client'),
      '$' || to_char(v_inv.total_cents / 100.0, 'FM999,990.00') || ' · created ' ||
        to_char(v_inv.created_at, 'Mon DD'),
      v_inv.id,
      v_inv.client_id,
      'awaiting_user',
      jsonb_build_object(
        'invoice_number', v_inv.invoice_number,
        'total_cents',    v_inv.total_cents,
        'invoice_date',   v_inv.invoice_date
      )
    )
    RETURNING id INTO v_thread_id;

    -- Greeting bot message (signed: Oracle)
    INSERT INTO public.assistant_messages (thread_id, role, content_type, content)
    VALUES (
      v_thread_id, 'bot', 'text',
      'Good morning — Oracle here. Invoice ' || v_inv.invoice_number || ' for $' ||
        to_char(v_inv.total_cents / 100.0, 'FM999,990.00') ||
        ' is ready to send to ' || COALESCE(v_inv.recipient_label, 'the parent') ||
        '. Want me to preview and send it?'
    );

    -- Action buttons message
    INSERT INTO public.assistant_messages (thread_id, role, content_type, content, metadata)
    VALUES (
      v_thread_id, 'bot', 'actions', NULL,
      jsonb_build_object('actions', jsonb_build_array(
        jsonb_build_object('key','preview_pdf',    'label','Preview PDF',   'style','ghost'),
        jsonb_build_object('key','send_now',       'label','Send to client', 'style','primary'),
        jsonb_build_object('key','snooze_3d',      'label','Remind in 3 days','style','ghost'),
        jsonb_build_object('key','resolve',        'label','I sent it myself','style','ghost')
      ))
    );

    v_count := v_count + 1;
  END LOOP;
  RETURN v_count;
END;
$func$;


-- ─── 7. Main scan RPC — runs all enabled detectors ───────────────────────
CREATE OR REPLACE FUNCTION public.assistant_scan_now()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  v_uid         uuid;
  v_owner_id    uuid;
  v_owner_count int := 0;
  v_inv_ready   int := 0;
  v_total       int := 0;
BEGIN
  v_uid := auth.uid();

  -- For now: run for the calling user (Caleb). Multi-user later picks
  -- this up by looping over all admins/owners.
  IF v_uid IS NULL THEN
    -- Cron context — find the OWNER role user
    SELECT user_id INTO v_owner_id
    FROM public.profiles
    WHERE role IN ('OWNER','SUPERADMIN','SuperAdmin','Owner')
    ORDER BY created_at
    LIMIT 1;
    IF v_owner_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'No owner user found for scan');
    END IF;
  ELSE
    v_owner_id := v_uid;
  END IF;

  -- Run each detector
  v_inv_ready := public.assistant_detect_invoice_ready_to_send(v_owner_id);

  -- (more detectors added in 19c.8b-c-d)

  v_total := v_inv_ready;

  RETURN jsonb_build_object(
    'ok',                        true,
    'owner_user_id',             v_owner_id,
    'invoice_ready_threads',     v_inv_ready,
    'total_threads_created',     v_total,
    'run_at',                    now()
  );
END;
$func$;
GRANT EXECUTE ON FUNCTION public.assistant_scan_now() TO authenticated;


-- ─── 8. List threads (with last-message summary + unread badge) ─────────
CREATE OR REPLACE FUNCTION public.assistant_list_threads(
  p_include_resolved boolean DEFAULT false
)
RETURNS TABLE (
  id              uuid,
  scenario_key    text,
  scenario_icon   text,
  title           text,
  subtitle        text,
  status          text,
  unread          boolean,
  invoice_id      uuid,
  client_id       uuid,
  last_message    text,
  last_message_at timestamptz,
  created_at      timestamptz,
  updated_at      timestamptz
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  RETURN QUERY
  SELECT
    t.id,
    t.scenario_key,
    s.icon,
    t.title,
    t.subtitle,
    t.status,
    t.unread_for_user,
    t.invoice_id,
    t.client_id,
    (SELECT m.content
     FROM public.assistant_messages m
     WHERE m.thread_id = t.id AND m.content_type IN ('text','event')
     ORDER BY m.created_at DESC LIMIT 1) AS last_message,
    (SELECT MAX(m.created_at) FROM public.assistant_messages m WHERE m.thread_id = t.id) AS last_message_at,
    t.created_at,
    t.updated_at
  FROM public.assistant_threads t
  LEFT JOIN public.assistant_scenarios s ON s.scenario_key = t.scenario_key
  WHERE t.owner_user_id = auth.uid()
    AND (p_include_resolved OR t.status IN ('open','awaiting_user','snoozed'))
  ORDER BY t.unread_for_user DESC, t.updated_at DESC;
END;
$func$;
GRANT EXECUTE ON FUNCTION public.assistant_list_threads(boolean) TO authenticated;


-- ─── 9. Get all messages for one thread (and mark it read) ──────────────
-- Note: must qualify `id` with table alias because the RETURN TABLE
-- has an `id` output column that shadows table column names without
-- explicit aliasing (Postgres throws "column reference id is ambiguous").
-- ────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.assistant_thread_messages(p_thread_id uuid)
RETURNS TABLE (
  id           uuid,
  role         text,
  content_type text,
  content      text,
  metadata     jsonb,
  created_at   timestamptz
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.assistant_threads t
    WHERE t.id = p_thread_id AND t.owner_user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Thread not found / not yours';
  END IF;

  -- Mark thread as read on open
  UPDATE public.assistant_threads AS t
  SET unread_for_user = false, updated_at = now()
  WHERE t.id = p_thread_id;

  RETURN QUERY
  SELECT m.id, m.role, m.content_type, m.content, m.metadata, m.created_at
  FROM public.assistant_messages m
  WHERE m.thread_id = p_thread_id
  ORDER BY m.created_at;
END;
$func$;
GRANT EXECUTE ON FUNCTION public.assistant_thread_messages(uuid) TO authenticated;


-- ─── 10. Post a user message ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.assistant_post_message(
  p_thread_id uuid,
  p_content   text
)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE v_id uuid;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin only'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.assistant_threads WHERE id = p_thread_id AND owner_user_id = auth.uid()) THEN
    RAISE EXCEPTION 'Thread not found / not yours';
  END IF;
  IF p_content IS NULL OR length(trim(p_content)) = 0 THEN
    RAISE EXCEPTION 'Empty message';
  END IF;

  INSERT INTO public.assistant_messages (thread_id, role, content_type, content)
  VALUES (p_thread_id, 'user', 'text', trim(p_content))
  RETURNING id INTO v_id;

  UPDATE public.assistant_threads SET updated_at = now() WHERE id = p_thread_id;
  RETURN v_id;
END;
$func$;
GRANT EXECUTE ON FUNCTION public.assistant_post_message(uuid, text) TO authenticated;


-- ─── 11. Action handler — handles button clicks (snooze, resolve, etc.) ─
-- Note: send_now / preview are handled client-side (browser renders the PDF
-- via the existing financial-pdf.js + sendFinancialEmail wrapper).
-- This RPC handles purely-server actions: snooze, resolve, dismiss.
-- ────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.assistant_action(
  p_thread_id uuid,
  p_action    text,
  p_payload   jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  v_thread record;
  v_event_msg text;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin only'; END IF;

  SELECT * INTO v_thread FROM public.assistant_threads
  WHERE id = p_thread_id AND owner_user_id = auth.uid();
  IF NOT FOUND THEN RAISE EXCEPTION 'Thread not found'; END IF;

  CASE p_action
    WHEN 'snooze_1d', 'snooze_3d', 'snooze_7d' THEN
      UPDATE public.assistant_threads
      SET status = 'snoozed',
          snoozed_until = now() + (CASE p_action
            WHEN 'snooze_1d' THEN interval '1 day'
            WHEN 'snooze_3d' THEN interval '3 days'
            ELSE interval '7 days' END),
          updated_at = now()
      WHERE id = p_thread_id;
      v_event_msg := 'Snoozed for ' || split_part(p_action, '_', 2);

    WHEN 'resolve' THEN
      UPDATE public.assistant_threads
      SET status = 'resolved',
          resolved_at = now(),
          resolved_by = auth.uid(),
          updated_at = now()
      WHERE id = p_thread_id;
      v_event_msg := 'Marked as handled';

    WHEN 'dismiss' THEN
      UPDATE public.assistant_threads
      SET status = 'dismissed',
          resolved_at = now(),
          resolved_by = auth.uid(),
          updated_at = now()
      WHERE id = p_thread_id;
      v_event_msg := 'Dismissed';

    WHEN 'reopen' THEN
      UPDATE public.assistant_threads
      SET status = 'awaiting_user',
          resolved_at = NULL, resolved_by = NULL,
          snoozed_until = NULL,
          updated_at = now()
      WHERE id = p_thread_id;
      v_event_msg := 'Reopened';

    WHEN 'mark_email_sent' THEN
      -- Client confirms the email was sent (after the JS preview→send flow)
      UPDATE public.assistant_threads
      SET status = 'resolved',
          resolved_at = now(),
          resolved_by = auth.uid(),
          updated_at = now()
      WHERE id = p_thread_id;
      v_event_msg := COALESCE(p_payload->>'event_text', 'Email sent ✓');

    ELSE
      RAISE EXCEPTION 'Unknown action: %', p_action;
  END CASE;

  -- Add a system event message so the thread reads as a real conversation
  INSERT INTO public.assistant_messages (thread_id, role, content_type, content, metadata)
  VALUES (p_thread_id, 'system', 'event', v_event_msg, p_payload);

  RETURN jsonb_build_object('ok', true, 'event', v_event_msg);
END;
$func$;
GRANT EXECUTE ON FUNCTION public.assistant_action(uuid, text, jsonb) TO authenticated;


-- ─── 12. Daily cron — runs scan at 16:00 UTC ────────────────────────────
-- One hour before the recurring-invoice cron (17:00 UTC) so the
-- assistant_scan picks up yesterday's new invoices first. Then the
-- next morning, the user opens the chat to find the threads already
-- waiting.
-- ────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule(jobid)
      FROM cron.job
      WHERE jobname = 'assistant-daily-scan';

    PERFORM cron.schedule(
      'assistant-daily-scan',
      '0 16 * * *',
      $cron$ SELECT public.assistant_scan_now(); $cron$
    );
    RAISE NOTICE 'pg_cron job scheduled: assistant-daily-scan at 16:00 UTC daily';
  ELSE
    RAISE WARNING 'pg_cron not installed — assistant cron skipped.';
  END IF;
END $$;


-- ─── 13. Verify ─────────────────────────────────────────────────────────
SELECT 'scenarios' AS what, count(*)::text AS value FROM public.assistant_scenarios
UNION ALL SELECT 'threads', count(*)::text FROM public.assistant_threads
UNION ALL SELECT 'messages', count(*)::text FROM public.assistant_messages
UNION ALL SELECT 'cron_active',
  COALESCE((SELECT active::text FROM cron.job WHERE jobname='assistant-daily-scan'), 'NOT SCHEDULED');

COMMIT;
